name: Invitation to the TechMart GitHub Community Organization
description: I would like to be part of the developers community
title: "Please invite me to the TechMart GitHub Community Organization"
labels: [invite me to the organisation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: discordname
    attributes:
      label: Insta Username (if applicable)
      placeholder: Insert your Instagram username here
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: What do you like about this community/Why do you want to join?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Join our Whatsapp Community [here](https://whatsapp.com/channel/0029ValjFriICVfpcV9HFc3b) to interact with 5k+ Developers from across the world!
        Follow our Telegram Page [here](https://t.me/all_technical_updates) for Internships, Jobs, Workshops, Events updates! 
        Feel free to check out our Bio Link [here](https://www.instagram.com/all_technical_updates) 🔥
