name: 🙋‍♂️ Request to Join TechMart Community
description: Request an invitation to join the TechMart Pune GitHub Organization
title: "Please invite me to the TechMart GitHub Community Organization"
labels: [invite me]
body:
  - type: input
    id: name
    attributes:
      label: Your Full Name
      placeholder: e.g., Vishwajeet Londhe
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why do you want to join?
      description: Tell us why you're interested in TechMart Pune
      placeholder: I want to contribute to open-source and grow with the community.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        👉 Join our WhatsApp Channel [here](https://whatsapp.com/channel/0029ValjFriICVfpcV9HFc3b) for regular TechMart updates.  
        👉 Follow our Instagram [here](https://www.instagram.com/all_technical_updates) for technical content.  
        👉 Explore TechMart [here](https://github.com/TechMart-Pune) 🔥
