name: Open Source Project Review
description: Please review my project on a livestream
title: "[REVIEW] <project name here>"
labels: [open source review, live stream review]
body:
  - type: markdown
    attributes:
      value: "Your project doesn't have to be hosted at GitHub, it can also be on GitLab or other VCS"
  - type: input
    id: link
    attributes:
      label: Project link
      placeholder: https://github.com/<your-username>/<project-name>
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Join our WhatsApp Channel [here](https://whatsapp.com/channel/0029ValjFriICVfpcV9HFc3b)
        Follow us on Telegram [here](https://t.me/all_technical_updates)
        Follow us on Instagram [here](https://www.instagram.com/all_technical_updates)
        Feel free to check out other cool repositories of the TechMart Community [here](https://github.com/TechMart-Pune)
