name: Resume Review
description: Please review my resume on a live stream
title: "[REVIEW]"
labels: [resume review, live stream review]
body:
  - type: markdown
    attributes:
      value: "**Remove all personal data, otherwise, the resume will be deleted**"
  - type: input
    id: link
    attributes:
      label: Resume link
      placeholder: "e.g.: https://drive.google.com/file/d/<file-id>/view"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Join our WhatsApp Channel [here](https://whatsapp.com/channel/0029ValjFriICVfpcV9HFc3b)
        Follow us on Telegram [here](https://t.me/all_technical_updates)
        Follow us on Instagram [here](https://www.instagram.com/all_technical_updates)
        Feel free to check out other cool repositories of the TechMart Community [here](https://github.com/TechMart-Pune)
